### ISSUE TITLE
Work-crime-rob

### ISSUE THREAD

**Issue by TypicalGhostGuy22** [RhykerWells/YAGPDB-ccs#15]
Copy and pasted the code from this file. When trying to save on website tells me there is an " template: :80: undefined variable "$user" ".

**Comment by RhykerWells** [comment]
Fixed in commit [8a8d945](https://github.com/Ranger-4297/YAGPDB-ccs/commit/8a8d945735aa2989bf1d3a3fc24e0d354c552ea0)
