### ISSUE TITLE
Fix `Event.cc.go` vars to match the ones in the code

### ISSUE THREAD

**Issue by EsenDR** [RhykerWells/YAGPDB-ccs#7]
Can't PR because I'm a bonobo with this stuff, BUT I thought I bring up to fix the vars in the Events CC since they're `$announcement...` instead of `$event...`.

**Comment by RhykerWells** [comment]
Ah, wow. Really? I hadn't noticed, nor do I think I would've. Will fix this in the next 5 mins. Thank you!
